---

- name: Install random password generator package
  apt: name={{item}} state=present
  with_items:
   - apg

- name: Random generate passwords
  command: apg -n {{ pass_cnt }} -M NCL -q
  register: passwdss

- name: Create users
  command: keystone --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }} 
           user-create --name={{ item.0 }} --pass={{ item.1 }}
  with_together:
    - userid
    - passwdss.stdout_lines

- name: Create user environments
  command: keystone --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }} 
           tenant-create --name={{ item }} --description="{{ item }}"
  with_items: tenantid

- name: Assign user to specified role in designated environment
  command: keystone --os-username={{ OS_USERNAME }} --os-password={{ OS_PASSWORD }} --os-tenant-name={{ OS_TENANT_NAME }} --os-auth-url={{ OS_AUTH_URL }}
           user-role-add --user={{ item.0 }} --tenant={{ item.1 }} --role={{ urole }}
  with_together: 
    - userid
    - tenantid
    
- name: User password assignment
  debug: msg="User {{ item.0 }} was added to {{ item.2 }} tenant, with the assigned password of {{ item.1 }}"
  with_together:
    - userid
    - passwdss.stdout_lines
    - tenantid