---
- name: Delete a user 
  os_user:
    state: absent
    name: "{{ item }}"
  with_items:
    - "{{ userid }}"
  

- name: Create Projects for Lab Users
  os_project:
    state: absent
    name: "{{ item }}"
  with_items:
    - "{{ tenantid }}"


